#!/bin/bash
python train.py --config cfgs/emotion/1_models/emotion_1_model_0.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_1.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_2.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_3.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_4.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_5.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_6.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_7.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_8.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_9.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_10.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_11.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_12.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_13.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_14.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_15.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_16.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_17.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_18.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_19.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_20.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_21.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_22.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_23.yml
python train.py --config cfgs/emotion/1_models/emotion_1_model_24.yml